# Generated by Django 5.0.7 on 2024-08-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="myconnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("levels", models.IntegerField(default=0)),
                ("experience", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("domain", models.CharField(max_length=50)),
                ("interest", models.CharField(max_length=50)),
            ],
        ),
    ]
